version: "3"

services:
  route-optimizer:
    build:
      context: ./route_optimizer
      dockerfile: .Dockerfile
    ports:
      - "8000:8000"
    networks:
      - sharedNetwork
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

networks:
  sharedNetwork:
    driver: bridge
